glyph.js:
	emcc -O3 \
	     --memory-init-file 0 \
	     -s NO_FILESYSTEM=1 \
	     -s MODULARIZE=1 \
	     -s PRECISE_F32=1 \
	     -s EXPORT_NAME="'GLYPHModule'" \
	     -s EXTRA_EXPORTED_RUNTIME_METHODS="['cwrap', 'malloc', 'free', 'writeArrayToMemory']" \
	     -s EXPORTED_FUNCTIONS="['_glyph_gen_keypair','_glyph_sign','_glyph_verify','_glyph_private_keysize','_glyph_public_keysize', '_glyph_signature_size']" \
	     -o glyph.js \
	     glyph/libglyph.a

clean:
	rm -f glyph.js
